<?php

return [
    'fund_source' => [
        'name' => ['required'],
        'amount' => ['required', 'numeric', 'min:1'],
        'year' => ['required', 'numeric', 'digits:4', 'min:2022'],
        'office_id' => ['required'],
    ],
    'wfp' => [
        'function_type' => ['required', 'in:Core,Strategy,Support'],
        'deliverables' => ['required'],
        'activities' => ['required'],
        'timeframe_from' => ['required', 'date'],
        'timeframe_to' => ['required', 'date', 'after_or_equal:timeframe_from'],
        'target_q1' => ['required'],
        'target_q2' => ['required'],
        'target_q3' => ['required'],
        'target_q4' => ['required'],
        'item' => ['required'],
        'cost' => ['required', 'numeric', 'min:1'],
        'fund_source_id' => ['required', 'exists:fund_sources,id'],
        'responsible_person_id' => ['required', 'numeric'],
    ],
    'ppmp' => [
        'wfp_id' => ['required', 'exists:wfps,id,status,approved'],
        'item_id' => ['required', 'exists:items,id'],
        'quantity' => ['required', 'numeric', 'min:1'],
        'unit' => ['required'],
        'abc' => ['required', 'numeric', 'min:1'],
        'procurement_mode' => ['required', 'in:Public Bidding,Shopping'],
        'milestone_1' => ['nullable', 'numeric'],
        'milestone_2' => ['nullable', 'numeric'],
        'milestone_3' => ['nullable', 'numeric'],
        'milestone_4' => ['nullable', 'numeric'],
        'milestone_5' => ['nullable', 'numeric'],
        'milestone_6' => ['nullable', 'numeric'],
        'milestone_7' => ['nullable', 'numeric'],
        'milestone_8' => ['nullable', 'numeric'],
        'milestone_9' => ['nullable', 'numeric'],
        'milestone_10' => ['nullable', 'numeric'],
        'milestone_11' => ['nullable', 'numeric'],
        'milestone_12' => ['nullable', 'numeric'],
    ],
];